### ISSUE TITLE
[Bug]: npm run dev: Unable to find the configuration file

### ISSUE THREAD

**Issue by sbaum2s** [beyondcode/herd-community#1000]
### Platform

Windows

### Operating system version

Windows 10 Pro 22H2 14.‎02.‎2022 19045.4894

### System architecture

Intel (x86)

### Herd Version

The latest as of September 2024

### PHP Version

PHP 8.2.3 (cli) (built: Feb 14 2023 09:55:52) (ZTS Visual C++ 2019 x64)

### Bug description

I have installed Herd von my Windows machine which created a separate issue (forcefully close all applications and trying to restart) Then in removed it again.
Then i run "npm run dev" on a Laravel project with no Herd or Valet packages involved and getting the error

error when starting dev server:
Error: Unable to find the configuration file [C:\Users\xxx\.config\herd\config\valet\config.json].

I deleted the "herd" folder and problem solved.

### Steps to reproduce

1. install Herd
2. remove it
3. run "npm run dev" in your laravel Project

### Relevant log output

```shell
error when starting dev server:
Error: Unable to find the configuration file [C:\Users\...\.config\herd\config\valet\config.json].
    at resolveDevelopmentEnvironmentTld (file:///C:/.../node_modules/laravel-vite-plugin/dist/index.js:358:11)
    at resolveDevelopmentEnvironmentServerConfig (file:///C:/.../node_modules/laravel-vite-plugin/dist/index.js:320:94)
    at config (file:///C:/.../node_modules/laravel-vite-plugin/dist/index.js:39:50)
    at runConfigHook (file:///C:/.../node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:66662:25)
    at async resolveConfig (file:///C:/.../node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:66111:12)
    at async _createServer (file:///C:/.../node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:62700:18)
    at async CAC.<anonymous> (file:///C:/.../node_modules/vite/dist/node/cli.js:735:20)
```

**Comment by sschlein** [comment]
Hey - we've fixed the restart after the setup that sometimes (!) happens when installing the VC redistributable  with the upcoming 1.11 release later this week.

If you're uninstalling Herd, also make sure to follow the additional steps listed at https://herd.laravel.com/docs/windows/1/troubleshooting/uninstalling . We can't do that automatically because there may be a ton of reasons why someone would keep them.

**Comment by sbaum2s** [comment]
> Hey - we've fixed the restart after the setup that sometimes (!) happens when installing the VC redistributable

You are right, this happens only sometimes. After that mishap i installed it on another machine with Windows 10 and it went smooth.

> If you're uninstalling Herd, also make sure to follow the additional steps listed at https://herd.laravel.com/docs/windows/1/troubleshooting/uninstalling . We can't do that automatically because there may be a ton of reasons why someone would keep them.

The thing with this approach is you need to be an Herd expert / read all docs because you just dont expect this. Not from a usual Windows program nor that it would break "npm run dev".
