### ISSUE TITLE
[Bug]: "Fatal error: Uncaught JsonException: Syntax error" when executing `herd` commands in terminal

### ISSUE THREAD

**Issue by pdipatrizio** [beyondcode/herd-community#1080]
### Platform

macOS

### Operating system version

macOS Sonoma 14.7 (23H124)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1 (Build: 34)

### PHP Version

8.3.12

### Bug description

`herd` commands in terminal give me this error:

```
Fatal error: Uncaught JsonException: Syntax error in phar:///Users/philip.dipatrizio/Library/Application Support/Herd/bin/herd.phar/cli/Valet/Configuration.php:155
Stack trace:
#0 phar:///Users/philip.dipatrizio/Library/Application Support/Herd/bin/herd.phar/cli/Valet/Configuration.php(155): json_decode('{\n    "tld": "t...', true, 512, 4194304)
#1 phar:///Users/philip.dipatrizio/Library/Application Support/Herd/bin/herd.phar/cli/includes/facades.php(22): Valet\Configuration->read()
#2 phar:///Users/philip.dipatrizio/Library/Application Support/Herd/bin/herd.phar/cli/app.php(53): Facade::__callStatic('read', Array)
#3 phar:///Users/philip.dipatrizio/Library/Application Support/Herd/bin/herd.phar/cli/herd.php(3): require_once('phar:///Users/p...')
#4 /Users/philip.dipatrizio/Library/Application Support/Herd/bin/herd.phar(12): require('phar:///Users/p...')
#5 {main}
  thrown in phar:///Users/philip.dipatrizio/Library/Application Support/Herd/bin/herd.phar/cli/Valet/Configuration.php on line 155
```

### Steps to reproduce

I'm not sure it's reproduceable on a fresh installation considering I can't find anyone else talking about it, but I have no idea why it's not working and could really use some help.

**Comment by pdipatrizio** [comment]
I figured it out... somehow a trailing comma got added to valet/config.json. I've never edited the config file directly so I'm not sure how it ended up there.

```
{
    "tld": "test",
    "loopback": "127.0.0.1",
    "paths": [
        "/Users/philip.dipatrizio/Library/Application Support/Herd/config/valet/Sites",
        "/Users/philip.dipatrizio/Library/Application Support/Herd/config/valet/Sites/",
        "/Users/philip.dipatrizio/Herd/"
    ],
    "share-tool": "expose",
}
```

Removing the `,` at the end of `"share-tool": "expose",` resolved it.

**Comment by pdipatrizio** [comment]
Not a bug. Turned out to be my fault :(
