### ISSUE TITLE
[Bug]: Unable to "npm run dev" on empty new JetStream project

### ISSUE THREAD

**Issue by emandtf** [beyondcode/herd-community#1211]
### Platform

Windows

### Operating system version

Windows 10 (22H2)

### System architecture

Intel (x86)

### Herd Version

1.13.0

### PHP Version

8.3.15

### Bug description

Unable to run Asset building using Vite.

I tried to manually execute "composer install" and "npm install" but both ended successfully without do any change.

### Steps to reproduce

The most simple way:

1. just download Herd
2. choose to create a New Site
3. select Jetstream
4. choose Livewire + Dark Mode + EmailVerification
5. set the destination folder

No any other file or setting changed.

### Relevant log output

```shell
Executing task: npm run dev 

> dev
> vite

X [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.dirname
        ╵ ~~~~~~

X [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.filename
        ╵ ~~~~~~

X [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.url
        ╵ ~~~~~~

failed to load config from C:\PHP\_Herd\test_jetstream\vite.config.js
error when starting dev server:
Error: Build failed with 3 errors:
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
    at failureErrorWithLog (C:\PHP\_Herd\test_jetstream\node_modules\esbuild\lib\main.js:1476:15)
    at C:\PHP\_Herd\test_jetstream\node_modules\esbuild\lib\main.js:945:25
    at runOnEndCallbacks (C:\PHP\_Herd\test_jetstream\node_modules\esbuild\lib\main.js:1316:45)
    at buildResponseToResult (C:\PHP\_Herd\test_jetstream\node_modules\esbuild\lib\main.js:943:7)
    at C:\PHP\_Herd\test_jetstream\node_modules\esbuild\lib\main.js:970:16
    at responseCallbacks.<computed> (C:\PHP\_Herd\test_jetstream\node_modules\esbuild\lib\main.js:622:9)
    at handleIncomingPacket (C:\PHP\_Herd\test_jetstream\node_modules\esbuild\lib\main.js:677:12)
    at Socket.readFromStdout (C:\PHP\_Herd\test_jetstream\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run dev" terminated with exit code: 1.
```

**Comment by tkuijer** [comment]
This appears to be a known Vite issue: https://github.com/vitejs/vite/issues/19018
workaround is to force esbuild to use version 0.24.0 instead:
`npm i -D esbuild@0.24.0`
