### ISSUE TITLE
[Bug]: Fatal error Class "ValetDriver" not found

### ISSUE THREAD

**Issue by mboisvertdupras** [beyondcode/herd-community#245]
### Operating system version

macOS Ventura 13.6

### System architecture

Intel (x86)

### Herd Version

1.3.1 (Build: 18)

### PHP Version

PHP 8.2

### Bug description

On a fresh install of Herd, migrating from Valet, I get this error on every single local site:

Fatal error: Uncaught Error: Class "ValetDriver" not found in /Users/marcboisvert/Library/Application Support/Herd/config/valet/Drivers/SampleValetDriver.php:3 Stack trace: #0 /Applications/Herd.app/Contents/Resources/valet/cli/Valet/Drivers/ValetDriver.php(97): require_once() #1 /Applications/Herd.app/Contents/Resources/valet/cli/Valet/Drivers/ValetDriver.php(122): Valet\Drivers\ValetDriver::driversIn('/Users/marcbois...') #2 /Applications/Herd.app/Contents/Resources/valet/cli/Valet/Drivers/ValetDriver.php(45): Valet\Drivers\ValetDriver::customDrivers() #3 /Applications/Herd.app/Contents/Resources/valet/server.php(54): Valet\Drivers\ValetDriver::assign('/Users/marcbois...', 'maisondelafamil...', '/devenir-membre...') #4 {main} thrown in /Users/marcboisvert/Library/Application Support/Herd/config/valet/Drivers/SampleValetDriver.php on line 3

### Steps to reproduce

1. Install Herd with a previous Valet installation
2. Try to visit a local site

**Comment by mpociot** [comment]
Did you migrate from an older version of Valet?
Your existing drivers get copied over. The correct class should contain this use statement:

use Valet\Drivers\ValetDriver;

**Comment by mboisvertdupras** [comment]
I don't think so, my current Valet version is 4.5.0 however I installed Herd at launch, had the same problem and deleted it. I did a reinstall by following the steps on the docs today and again, the same error. Perhaps there's something left over that needs to be deleted?

**Comment by mboisvertdupras** [comment]
I deleted everything in the Drivers directory in /Users/{my-user}/Library/Application Support/Herd/config/valet/Drivers and it seems to be working now.

**Comment by larsbo** [comment]
My drivers have not been copied automatically during Herd installation.
So I copied `~/.config/valet/Drivers` into `~/Library/Application Support/Herd/config/valet/Drivers` and Herd is working with custom drivers.
