### ISSUE TITLE
[Bug]: Herd Pro Mail service doesn't start

### ISSUE THREAD

**Issue by ryanmortier** [beyondcode/herd-community#404]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.1 (Build: 21)

### PHP Version

PHP 8.2.15 (cli) (built: Jan 19 2024 00:15:08) (NTS)

### Bug description

See log:

```
Port 2525 is free. Starting mailserver.
Mailserver listening on port 2525
node:events:515
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (/snapshot/herd-mailserver/node_modules/ws/lib/websocket.js:292:7)
    at ReconnectingWebSocket._disconnect (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:541:22)
    at ReconnectingWebSocket._handleError (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:180:19)
    at ReconnectingWebSocket._handleTimeout (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:531:14)
    at Timeout.<anonymous> (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:526:75)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/snapshot/herd-mailserver/node_modules/ws/lib/websocket.js:1033:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.5.0
```

**Comment by mpociot** [comment]
Can you can you please modify the port (just remove and re-add a digit to let it restart) and see if that fixes the issue?
You might need to do the same thing for the "dump server" port which is used internally.

**Comment by ryanmortier** [comment]
That works for the mail server but not dump server:

![CleanShot 2024-02-14 at 10 22 13](https://github.com/beyondcode/herd-community/assets/2053960/44bf4169-ce00-49e9-8d35-b7576d8003b8)

![CleanShot 2024-02-14 at 10 22 29](https://github.com/beyondcode/herd-community/assets/2053960/7753bade-98e6-4968-9f40-2e0849b957bf)

Does this have anything to do with me having `HELO` installed (but not currently running)?

**Comment by ryanmortier** [comment]
I ended up doing an `option` force stop in the Herd dropdown menu and then started all services again which has resolved the issue. Though if I do a reboot, the issue comes back. Not an urgency anymore as I have a fix but weird that a reboot doesn't fix the issue.

**Comment by mpociot** [comment]
Do you still have this issue? I am unable to reproduce this

**Comment by ryanmortier** [comment]
I do but not all the time. It might just be something conflicting on my own machine. I'll close this.

**Comment by renzocastillo** [comment]
I also happen to have the same issue on my M1 Mac. I only have Herd Pro installed, not even valet or something that could interfere. 

Operating system version
macOS Sonoma 14.3.1

System architecture
ARM64 (M1, M2, etc)

Herd Version
1.6.0 (Build: 24)

PHP Version
PHP 7.4.33 (cli) 

Bug description

```
lsof -nP -iTCP -sTCP:LISTEN | grep 2525
mailserve 10493 renzocastillo   22u  IPv6 0x7fea404ec7ded21b      0t0  TCP *:2525 (LISTEN)
```

<img width="906" alt="image" src="https://github.com/beyondcode/herd-community/assets/21372177/8d3a1c67-90f9-4763-8782-063d92809107">

**Comment by stefro** [comment]
I'm having the exact same issue. I've just performed a "clean install" of MacOS and instead of all the usual homebrew packages I'm using Herd Pro. So nothing else is running in the background.

I'm getting this:
```
Port 2525 is free. Starting mailserver.
Mailserver listening on port 2525
node:events:515
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (/snapshot/herd-mailserver/node_modules/ws/lib/websocket.js:292:7)
    at ReconnectingWebSocket._disconnect (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:541:22)
    at ReconnectingWebSocket._handleError (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:180:19)
    at ReconnectingWebSocket._handleTimeout (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:531:14)
    at Timeout.<anonymous> (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:526:75)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/snapshot/herd-mailserver/node_modules/ws/lib/websocket.js:1033:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.5.0
```

When I click "Stop all" from the Herd menu, and than "Start all", it will work. But after a while (few minutes or a few hours), it will stop the mail and dump service with the same message (above).
