### ISSUE TITLE
[Bug]:  could not find driver (sqlite)

### ISSUE THREAD

**Issue by Gary11777** [beyondcode/herd-community#831]
### Platform

Windows

### Operating system version

Windows 11 (23H2 22631.3737)

### System architecture

Intel (x86)

### Herd Version

1.7.2

### PHP Version

PHP 8.3.8

### Bug description

**### I kindly ask You help me with the following problem. Thank you!

When I try to run the migration command "php artisan migrate:fresh" there is an exception:**

> D:\Projects\laravel_herd_projects\example git:[15_seeders]
> php artisan migrate:fresh
> 
>    Illuminate\Database\QueryException 
> 
>   could not find driver (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;)
> 
>   at vendor\laravel\framework\src\Illuminate\Database\Connection.php:813
>     809▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
>     810▕                 );
>     811▕             }
>     812▕ 
>   ➜ 813▕             throw new QueryException(
>     814▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
>     815▕             );
>     816▕         }
>     817▕     }
> 
>   1   vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:65
>       PDOException::("could not find driver")
> 
>   2   vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:65
>       PDO::__construct("sqlite:D:\Projects\laravel_herd_projects\example\database\database.sqlite", Object(SensitiveParameterValue), [])

**### There is a database.sqlite (D:\Projects\laravel_herd_projects\example\database\database.sqlite).**

**### .env**
> DB_CONNECTION=sqlite
> DB_DATABASE=D:\Projects\laravel_herd_projects\example\database\database.sqlite

**### php.ini**
> extension=pdo_sqlite
> extension=sqlite3

**### config/database.php**
> 'connections' => [
> 
>         'sqlite' => [
>             'driver' => 'sqlite',
>             'url' => env('DB_URL'),
>             'database' => env('DB_DATABASE', database_path('database.sqlite')),
>             'prefix' => '',
>             'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
>         ],

**### phpinfo:**
![image](https://github.com/beyondcode/herd-community/assets/74620786/c4f0c29f-5889-4574-a5f7-3eb916326a76)

![image](https://github.com/beyondcode/herd-community/assets/74620786/df907dfd-d12a-45ad-818e-42c27ffec741)

### Relevant log output

```shell
[2024-06-21 10:00:32] local.ERROR: Debugbar exception: Database file at path [database/database.sqlite] does not exist. Ensure this is an absolute path to the database. (Connection: sqlite, SQL: select * from "sessions" where "id" = 0oZqL8ZCnQ7CVywTu2hecDFsfiKJhttxcxUh6ZG1 limit 1)  
[2024-06-21 10:03:56] local.ERROR: could not find driver (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;) at D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:813)
[stacktrace]
#0 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(767): Illuminate\\Database\\Connection->runQueryCallback('PRAGMA foreign_...', Array, Object(Closure))
#1 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(560): Illuminate\\Database\\Connection->run('PRAGMA foreign_...', Array, Object(Closure))
#2 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Builder.php(522): Illuminate\\Database\\Connection->statement('PRAGMA foreign_...')
#3 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\SQLiteConnection.php(38): Illuminate\\Database\\Schema\\Builder->enableForeignKeyConstraints()
#4 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(275): Illuminate\\Database\\SQLiteConnection->__construct(Object(Closure), 'D:\\\\Projects\\\\lar...', '', Array)
#5 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(76): Illuminate\\Database\\Connectors\\ConnectionFactory->createConnection('sqlite', Object(Closure), 'D:\\\\Projects\\\\lar...', '', Array)
#6 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(51): Illuminate\\Database\\Connectors\\ConnectionFactory->createSingleConnection(Array)
#7 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(167): Illuminate\\Database\\Connectors\\ConnectionFactory->make(Array, 'sqlite')
#8 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(93): Illuminate\\Database\\DatabaseManager->makeConnection('sqlite')
#9 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\DatabaseMigrationRepository.php(226): Illuminate\\Database\\DatabaseManager->connection('sqlite')
#10 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\DatabaseMigrationRepository.php(182): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->getConnection()
#11 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(689): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#12 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\FreshCommand.php(66): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#13 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(622): Illuminate\\Database\\Console\\Migrations\\FreshCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#14 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\FreshCommand.php(65): Illuminate\\Database\\Migrations\\Migrator->usingConnection(NULL, Object(Closure))
#15 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\FreshCommand->handle()
#16 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#18 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#19 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#20 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(212): Illuminate\\Container\\Container->call(Array)
#21 D:\\Projects\\laravel_herd_projects\\example\\vendor\\symfony\\console\\Command\\Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(181): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 D:\\Projects\\laravel_herd_projects\\example\\vendor\\symfony\\console\\Application.php(1049): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 D:\\Projects\\laravel_herd_projects\\example\\vendor\\symfony\\console\\Application.php(318): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\FreshCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 D:\\Projects\\laravel_herd_projects\\example\\vendor\\symfony\\console\\Application.php(169): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(196): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1187): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 D:\\Projects\\laravel_herd_projects\\example\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#29 {main}

[previous exception] [object] (PDOException(code: 0): could not find driver at D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php:65)
[stacktrace]
#0 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php(65): PDO->__construct('sqlite:D:\\\\Proje...', NULL, Object(SensitiveParameterValue), Array)
#1 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('sqlite:D:\\\\Proje...', NULL, NULL, Array)
#2 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\SQLiteConnector.php(37): Illuminate\\Database\\Connectors\\Connector->createConnection('sqlite:D:\\\\Proje...', Array, Array)
#3 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(222): Illuminate\\Database\\Connectors\\SQLiteConnector->connect(Array)
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(1219): call_user_func(Object(Closure))
#6 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(565): Illuminate\\Database\\Connection->getPdo()
#7 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(800): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('PRAGMA foreign_...', Array)
#8 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(767): Illuminate\\Database\\Connection->runQueryCallback('PRAGMA foreign_...', Array, Object(Closure))
#9 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(560): Illuminate\\Database\\Connection->run('PRAGMA foreign_...', Array, Object(Closure))
#10 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Builder.php(522): Illuminate\\Database\\Connection->statement('PRAGMA foreign_...')
#11 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\SQLiteConnection.php(38): Illuminate\\Database\\Schema\\Builder->enableForeignKeyConstraints()
#12 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(275): Illuminate\\Database\\SQLiteConnection->__construct(Object(Closure), 'D:\\\\Projects\\\\lar...', '', Array)
#13 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(76): Illuminate\\Database\\Connectors\\ConnectionFactory->createConnection('sqlite', Object(Closure), 'D:\\\\Projects\\\\lar...', '', Array)
#14 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(51): Illuminate\\Database\\Connectors\\ConnectionFactory->createSingleConnection(Array)
#15 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(167): Illuminate\\Database\\Connectors\\ConnectionFactory->make(Array, 'sqlite')
#16 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(93): Illuminate\\Database\\DatabaseManager->makeConnection('sqlite')
#17 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\DatabaseMigrationRepository.php(226): Illuminate\\Database\\DatabaseManager->connection('sqlite')
#18 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\DatabaseMigrationRepository.php(182): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->getConnection()
#19 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(689): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#20 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\FreshCommand.php(66): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#21 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(622): Illuminate\\Database\\Console\\Migrations\\FreshCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#22 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\FreshCommand.php(65): Illuminate\\Database\\Migrations\\Migrator->usingConnection(NULL, Object(Closure))
#23 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\FreshCommand->handle()
#24 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#26 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#27 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#28 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(212): Illuminate\\Container\\Container->call(Array)
#29 D:\\Projects\\laravel_herd_projects\\example\\vendor\\symfony\\console\\Command\\Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(181): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#31 D:\\Projects\\laravel_herd_projects\\example\\vendor\\symfony\\console\\Application.php(1049): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 D:\\Projects\\laravel_herd_projects\\example\\vendor\\symfony\\console\\Application.php(318): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\FreshCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 D:\\Projects\\laravel_herd_projects\\example\\vendor\\symfony\\console\\Application.php(169): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(196): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 D:\\Projects\\laravel_herd_projects\\example\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1187): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 D:\\Projects\\laravel_herd_projects\\example\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#37 {main}
"}
```

**Comment by Gary11777** [comment]
**### .env**
DB_CONNECTION=sqlite
DB_DATABASE=D:\Projects\laravel_herd_projects\example\database\database.sqlite

**Comment by am-coding-com** [comment]
I have a related problem (Windows): 

Serving the site in the browser using herd is working: https://example.test

this is working:
`php artisan queue:work`

this does not work 
`herd debug artisan queue:work`
I get the same error:

> could not find driver (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;)

**Comment by Gary11777** [comment]
**### phpinfo:**
![изображение_2024-06-24_085547536](https://github.com/beyondcode/herd-community/assets/74620786/5610ba82-d58c-4868-86dd-743303b12b82)
![изображение_2024-06-24_085643682](https://github.com/beyondcode/herd-community/assets/74620786/436bb151-d6ee-4ebb-b71c-1e26637e3fbc)

**Comment by Gary11777** [comment]
There is a message "**Connection failed: SQLSTATE[HY000] [14] unable to open database file**" when I run a PHP script to test the PDO SQLite connection: 

_<?php
try {
    $pdo = new PDO('sqlite:' . __DIR__ . '/database/database.sqlite');
    echo 'Connection successful!';
} catch (PDOException $e) {
    echo 'Connection failed: ' . $e->getMessage();
}_

**Comment by Gary11777** [comment]
**There is a result:**
> Database path: D:\Projects\laravel_herd_projects\example\database\database.sqlite File exists! Connection successful!

**when I run the following test script:**
> <?php
> $dbPath = 'D:\Projects\laravel_herd_projects\example\database\database.sqlite';
> echo "Database path: $dbPath\n";
> if (file_exists($dbPath)) {
>     echo "File exists!\n";
>     try {
>         $pdo = new PDO('sqlite:' . $dbPath);
>         echo 'Connection successful!';
>     } catch (PDOException $e) {
>         echo 'Connection failed: ' . $e->getMessage();
>     }
> } else {
>     echo "File does not exist!\n";
> }

**Comment by Gary11777** [comment]
**There is a result:**
> Database path: D:\Projects\laravel_herd_projects\example\database\database.sqlite File exists! Connection successful!

**when I run the following test script:**
_<?php
$dbPath = 'D:\Projects\laravel_herd_projects\example\database\database.sqlite';
echo "Database path: $dbPath\n";
if (file_exists($dbPath)) {
    echo "File exists!\n";
    try {
        $pdo = new PDO('sqlite:' . $dbPath);
        echo 'Connection successful!';
    } catch (PDOException $e) {
        echo 'Connection failed: ' . $e->getMessage();
    }
} else {
    echo "File does not exist!\n";
}_

**Comment by sschlein** [comment]
What happens if you run one of these commands?

```
herd php artisan mirgate
php83 artisan migrate
```

My guess is that your terminal is linked to an old php version from a previous set and that does not have the driver but when running it through nginx, it does work because it uses php from Herd.

**Comment by Gary11777** [comment]
Thank you! 
It's works. 
I run the command 
> herd php artisan migrate:fresh

**Comment by Gary11777** [comment]
> What happens if you run one of these commands?
> 
> ```
> herd php artisan mirgate
> php83 artisan migrate
> ```
> 
> My guess is that your terminal is linked to an old php version from a previous set and that does not have the driver but when running it through nginx, it does work because it uses php from Herd.

Thank you very much! 
It's works. 
I run the command 
> ```
> herd php artisan migrate:fresh
> ```

**Comment by sschlein** [comment]
I assume there is a problem with your environment variable on your system and that an old existing php is mentioned before the Herd bin path.

**Comment by Gary11777** [comment]
> I assume there is a problem with your environment variable on your system and that an old existing php is mentioned before the Herd bin path.

> I assume there is a problem with your environment variable on your system and that an old existing php is mentioned before the Herd bin path.

**The Herd bin path is the first:**
![изображение_2024-06-24_120850769](https://github.com/beyondcode/herd-community/assets/74620786/4319b226-2b2e-4949-bebb-2dca5a851db2)

**Comment by sschlein** [comment]
Is there a 2nd path variable on system level?

**Comment by Gary11777** [comment]
Yes. System variables in the second window:
![изображение_2024-06-24_131711653](https://github.com/beyondcode/herd-community/assets/74620786/f9b7ff06-2d97-4625-bf68-7862947b95d3)
