### ISSUE TITLE
[Bug]: Herd fresh install of laravel jetstream w/Teams "Unhandled match case '60'"

### ISSUE THREAD

**Issue by StealthMicro** [beyondcode/herd-community#883]
### Platform

macOS

### Operating system version

macOS Sequoia

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1

### PHP Version

PHP 8.3.9

### Bug description

When you register a user and it takes you to the dashboard you receive the "Unhandled match case '60'"

This only happens when you select JetStream with Teams.

### Steps to reproduce

Fresh installation of Laravel.  Select Jetstream and check the Teams checkbox.

Then register a user and when it redirects to the Dashboard you get that error.

### Relevant log output

```shell
[2024-07-15 17:58:58] local.ERROR: Unhandled match case '60' (View: /Users/robert/Herd/laravel11-jetstream-teams/resources/views/components/dropdown.blade.php) (View: /Users/robert/Herd/laravel11-jetstream-teams/resources/views/components/dropdown.blade.php) (View: /Users/robert/Herd/laravel11-jetstream-teams/resources/views/components/dropdown.blade.php) (View: /Users/robert/Herd/laravel11-jetstream-teams/resources/views/components/dropdown.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Unhandled match case '60' (View: /Users/robert/Herd/laravel11-jetstream-teams/resources/views/components/dropdown.blade.php) (View: /Users/robert/Herd/laravel11-jetstream-teams/resources/views/components/dropdown.blade.php) (View: /Users/robert/Herd/laravel11-jetstream-teams/resources/views/components/dropdown.blade.php) (View: /Users/robert/Herd/laravel11-jetstream-teams/resources/views/components/dropdown.blade.php) at /Users/robert/Herd/laravel11-jetstream-teams/storage/framework/views/e804a5e92f7884c40ffa30581ffe50d0.php:40)
[stacktrace]
#0 /Users/robert/Herd/laravel11-jetstream-teams/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(58): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(Illuminate\\View\\ViewException), 1)
#1 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->handleViewException(Object(Illuminate\\View\\ViewException), 1)
#2 /Users/robert/Herd/laravel11-jetstream-teams/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(22): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/Users/robert/H...', Array)
#3 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(73): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->evaluatePath('/Users/robert/H...', Array)
#4 /Users/robert/Herd/laravel11-jetstream-teams/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(10): Illuminate\\View\\Engines\\CompilerEngine->get('/Users/robert/H...', Array)
#5 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/View/View.php(208): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->get('/Users/robert/H...', Array)
#6 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/View/View.php(191): Illuminate\\View\\View->getContents()
#7 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/View/View.php(160): Illuminate\\View\\View->renderContents()
#8 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\\View\\View->render()
#9 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#10 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(920): Illuminate\\Http\\Response->__construct(Object(Illuminate\\View\\View), 200, Array)
#11 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(887): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#12 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#13 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\EnsureEmailIsVerified->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(64): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'sanctum')
#22 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#28 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#36 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#37 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#38 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#39 /Users/robert/Herd/laravel11-jetstream-teams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/robert/Herd/laravel11-jetstream-teams/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
```

**Comment by eliascotto** [comment]
Temporary solved it by modifying `resources/views/components/dropdown.blade.php`

```
$width = match ($width) {
    '48' => 'w-48',
    '60' => 'w-48',
};
```

**Comment by DanielSpravtsev** [comment]
Same issue after installing fresh jetstream using Valet, so this is not Herd issue
